# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/amiralirajan/projects/sdl-2d-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/amiralirajan/projects/sdl-2d-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amiralirajan/projects/sdl-2d-game/CMakeFiles /Users/amiralirajan/projects/sdl-2d-game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amiralirajan/projects/sdl-2d-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdl-2d-game

# Build rule for target.
sdl-2d-game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdl-2d-game
.PHONY : sdl-2d-game

# fast build rule for target.
sdl-2d-game/fast:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/build
.PHONY : sdl-2d-game/fast

AnimatedSprite.o: AnimatedSprite.cpp.o

.PHONY : AnimatedSprite.o

# target to build an object file
AnimatedSprite.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/AnimatedSprite.cpp.o
.PHONY : AnimatedSprite.cpp.o

AnimatedSprite.i: AnimatedSprite.cpp.i

.PHONY : AnimatedSprite.i

# target to preprocess a source file
AnimatedSprite.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/AnimatedSprite.cpp.i
.PHONY : AnimatedSprite.cpp.i

AnimatedSprite.s: AnimatedSprite.cpp.s

.PHONY : AnimatedSprite.s

# target to generate assembly for a file
AnimatedSprite.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/AnimatedSprite.cpp.s
.PHONY : AnimatedSprite.cpp.s

FPS.o: FPS.cpp.o

.PHONY : FPS.o

# target to build an object file
FPS.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/FPS.cpp.o
.PHONY : FPS.cpp.o

FPS.i: FPS.cpp.i

.PHONY : FPS.i

# target to preprocess a source file
FPS.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/FPS.cpp.i
.PHONY : FPS.cpp.i

FPS.s: FPS.cpp.s

.PHONY : FPS.s

# target to generate assembly for a file
FPS.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/FPS.cpp.s
.PHONY : FPS.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Game.cpp.s
.PHONY : Game.cpp.s

Input.o: Input.cpp.o

.PHONY : Input.o

# target to build an object file
Input.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Input.cpp.o
.PHONY : Input.cpp.o

Input.i: Input.cpp.i

.PHONY : Input.i

# target to preprocess a source file
Input.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Input.cpp.i
.PHONY : Input.cpp.i

Input.s: Input.cpp.s

.PHONY : Input.s

# target to generate assembly for a file
Input.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Input.cpp.s
.PHONY : Input.cpp.s

OS.o: OS.cpp.o

.PHONY : OS.o

# target to build an object file
OS.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/OS.cpp.o
.PHONY : OS.cpp.o

OS.i: OS.cpp.i

.PHONY : OS.i

# target to preprocess a source file
OS.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/OS.cpp.i
.PHONY : OS.cpp.i

OS.s: OS.cpp.s

.PHONY : OS.s

# target to generate assembly for a file
OS.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/OS.cpp.s
.PHONY : OS.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Player.cpp.s
.PHONY : Player.cpp.s

Renderer.o: Renderer.cpp.o

.PHONY : Renderer.o

# target to build an object file
Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Renderer.cpp.o
.PHONY : Renderer.cpp.o

Renderer.i: Renderer.cpp.i

.PHONY : Renderer.i

# target to preprocess a source file
Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Renderer.cpp.i
.PHONY : Renderer.cpp.i

Renderer.s: Renderer.cpp.s

.PHONY : Renderer.s

# target to generate assembly for a file
Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Renderer.cpp.s
.PHONY : Renderer.cpp.s

Sprite.o: Sprite.cpp.o

.PHONY : Sprite.o

# target to build an object file
Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Sprite.cpp.o
.PHONY : Sprite.cpp.o

Sprite.i: Sprite.cpp.i

.PHONY : Sprite.i

# target to preprocess a source file
Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Sprite.cpp.i
.PHONY : Sprite.cpp.i

Sprite.s: Sprite.cpp.s

.PHONY : Sprite.s

# target to generate assembly for a file
Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Sprite.cpp.s
.PHONY : Sprite.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

json-parser/json.o: json-parser/json.c.o

.PHONY : json-parser/json.o

# target to build an object file
json-parser/json.c.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/json-parser/json.c.o
.PHONY : json-parser/json.c.o

json-parser/json.i: json-parser/json.c.i

.PHONY : json-parser/json.i

# target to preprocess a source file
json-parser/json.c.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/json-parser/json.c.i
.PHONY : json-parser/json.c.i

json-parser/json.s: json-parser/json.c.s

.PHONY : json-parser/json.s

# target to generate assembly for a file
json-parser/json.c.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/json-parser/json.c.s
.PHONY : json-parser/json.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sdl-2d-game.dir/build.make CMakeFiles/sdl-2d-game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sdl-2d-game"
	@echo "... AnimatedSprite.o"
	@echo "... AnimatedSprite.i"
	@echo "... AnimatedSprite.s"
	@echo "... FPS.o"
	@echo "... FPS.i"
	@echo "... FPS.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Input.o"
	@echo "... Input.i"
	@echo "... Input.s"
	@echo "... OS.o"
	@echo "... OS.i"
	@echo "... OS.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Renderer.o"
	@echo "... Renderer.i"
	@echo "... Renderer.s"
	@echo "... Sprite.o"
	@echo "... Sprite.i"
	@echo "... Sprite.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... json-parser/json.o"
	@echo "... json-parser/json.i"
	@echo "... json-parser/json.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

